name: iot_client_starter
description: A starter package for iot client.
version: 1.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <3.5.0'

dependencies:
  #Network
  websocket_universal: ^1.1.1

  #Architecture
  bloc: ^8.1.0

  #Data
  freezed_annotation: ^2.2.0

  iot_internal:
    git:
      url: https://github.com/NikitaMasev/iot_internal.git
      ref: main

dev_dependencies:
  freezed: ^2.3.0
  lints: ^2.0.0
  build_runner: ^2.3.2
