name: iot_client_starter
description: A starter package for iot client.
version: 1.1.2
publish_to: none

environment:
  sdk: '>=3.0.0 <3.5.0'

dependencies:
  #Network
  websocket_universal: ^1.1.1

  iot_internal:
    git:
      url: https://github.com/NikitaMasev/iot_internal.git
      ref: main

dev_dependencies:
  freezed: ^2.4.2
  lints: ^2.1.1
  build_runner: ^2.4.6
